Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: transformers in /home/mkoopmans/.local/lib/python3.11/site-packages (4.44.0)
Requirement already satisfied: torch in /home/mkoopmans/.local/lib/python3.11/site-packages (2.4.0)
Requirement already satisfied: tqdm in /home/mkoopmans/.local/lib/python3.11/site-packages (4.66.5)
Requirement already satisfied: numpy in /home/mkoopmans/.local/lib/python3.11/site-packages (1.26.4)
Requirement already satisfied: datasets in /home/mkoopmans/.local/lib/python3.11/site-packages (2.20.0)
Requirement already satisfied: accelerate in /home/mkoopmans/.local/lib/python3.11/site-packages (0.33.0)
Requirement already satisfied: matplotlib in /home/mkoopmans/.local/lib/python3.11/site-packages (3.9.1.post1)
Requirement already satisfied: scikit-learn in /home/mkoopmans/.local/lib/python3.11/site-packages (1.5.1)
Requirement already satisfied: filelock in /home/mkoopmans/.local/lib/python3.11/site-packages (from transformers) (3.15.4)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /home/mkoopmans/.local/lib/python3.11/site-packages (from transformers) (0.24.5)
Requirement already satisfied: packaging>=20.0 in /sw/arch/RHEL8/EB_production/2023/software/Python/3.11.3-GCCcore-12.3.0/lib/python3.11/site-packages (from transformers) (23.1)
Requirement already satisfied: pyyaml>=5.1 in /home/mkoopmans/.local/lib/python3.11/site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /home/mkoopmans/.local/lib/python3.11/site-packages (from transformers) (2024.7.24)
Requirement already satisfied: requests in /home/mkoopmans/.local/lib/python3.11/site-packages (from transformers) (2.32.3)
Requirement already satisfied: safetensors>=0.4.1 in /home/mkoopmans/.local/lib/python3.11/site-packages (from transformers) (0.4.4)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /home/mkoopmans/.local/lib/python3.11/site-packages (from transformers) (0.19.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /home/mkoopmans/.local/lib/python3.11/site-packages (from torch) (4.12.2)
Requirement already satisfied: sympy in /home/mkoopmans/.local/lib/python3.11/site-packages (from torch) (1.13.1)
Requirement already satisfied: networkx in /home/mkoopmans/.local/lib/python3.11/site-packages (from torch) (3.3)
Requirement already satisfied: jinja2 in /home/mkoopmans/.local/lib/python3.11/site-packages (from torch) (3.1.4)
Requirement already satisfied: fsspec in /home/mkoopmans/.local/lib/python3.11/site-packages (from torch) (2024.5.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /home/mkoopmans/.local/lib/python3.11/site-packages (from torch) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /home/mkoopmans/.local/lib/python3.11/site-packages (from torch) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /home/mkoopmans/.local/lib/python3.11/site-packages (from torch) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /home/mkoopmans/.local/lib/python3.11/site-packages (from torch) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /home/mkoopmans/.local/lib/python3.11/site-packages (from torch) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /home/mkoopmans/.local/lib/python3.11/site-packages (from torch) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /home/mkoopmans/.local/lib/python3.11/site-packages (from torch) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /home/mkoopmans/.local/lib/python3.11/site-packages (from torch) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /home/mkoopmans/.local/lib/python3.11/site-packages (from torch) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in /home/mkoopmans/.local/lib/python3.11/site-packages (from torch) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /home/mkoopmans/.local/lib/python3.11/site-packages (from torch) (12.1.105)
Requirement already satisfied: triton==3.0.0 in /home/mkoopmans/.local/lib/python3.11/site-packages (from torch) (3.0.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /home/mkoopmans/.local/lib/python3.11/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch) (12.6.20)
Requirement already satisfied: pyarrow>=15.0.0 in /home/mkoopmans/.local/lib/python3.11/site-packages (from datasets) (17.0.0)
Requirement already satisfied: pyarrow-hotfix in /home/mkoopmans/.local/lib/python3.11/site-packages (from datasets) (0.6)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /home/mkoopmans/.local/lib/python3.11/site-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /home/mkoopmans/.local/lib/python3.11/site-packages (from datasets) (2.2.2)
Requirement already satisfied: xxhash in /home/mkoopmans/.local/lib/python3.11/site-packages (from datasets) (3.4.1)
Requirement already satisfied: multiprocess in /home/mkoopmans/.local/lib/python3.11/site-packages (from datasets) (0.70.16)
Requirement already satisfied: aiohttp in /home/mkoopmans/.local/lib/python3.11/site-packages (from datasets) (3.10.3)
Requirement already satisfied: psutil in /home/mkoopmans/.local/lib/python3.11/site-packages (from accelerate) (6.0.0)
Requirement already satisfied: contourpy>=1.0.1 in /home/mkoopmans/.local/lib/python3.11/site-packages (from matplotlib) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /home/mkoopmans/.local/lib/python3.11/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/mkoopmans/.local/lib/python3.11/site-packages (from matplotlib) (4.53.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/mkoopmans/.local/lib/python3.11/site-packages (from matplotlib) (1.4.5)
Requirement already satisfied: pillow>=8 in /home/mkoopmans/.local/lib/python3.11/site-packages (from matplotlib) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /home/mkoopmans/.local/lib/python3.11/site-packages (from matplotlib) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /home/mkoopmans/.local/lib/python3.11/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: scipy>=1.6.0 in /home/mkoopmans/.local/lib/python3.11/site-packages (from scikit-learn) (1.14.0)
Requirement already satisfied: joblib>=1.2.0 in /home/mkoopmans/.local/lib/python3.11/site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /home/mkoopmans/.local/lib/python3.11/site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /home/mkoopmans/.local/lib/python3.11/site-packages (from aiohttp->datasets) (2.3.5)
Requirement already satisfied: aiosignal>=1.1.2 in /home/mkoopmans/.local/lib/python3.11/site-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /home/mkoopmans/.local/lib/python3.11/site-packages (from aiohttp->datasets) (24.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/mkoopmans/.local/lib/python3.11/site-packages (from aiohttp->datasets) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/mkoopmans/.local/lib/python3.11/site-packages (from aiohttp->datasets) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /home/mkoopmans/.local/lib/python3.11/site-packages (from aiohttp->datasets) (1.9.4)
Requirement already satisfied: six>=1.5 in /home/mkoopmans/.local/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/mkoopmans/.local/lib/python3.11/site-packages (from requests->transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /home/mkoopmans/.local/lib/python3.11/site-packages (from requests->transformers) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/mkoopmans/.local/lib/python3.11/site-packages (from requests->transformers) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /home/mkoopmans/.local/lib/python3.11/site-packages (from requests->transformers) (2024.7.4)
Requirement already satisfied: MarkupSafe>=2.0 in /home/mkoopmans/.local/lib/python3.11/site-packages (from jinja2->torch) (2.1.5)
Requirement already satisfied: pytz>=2020.1 in /home/mkoopmans/.local/lib/python3.11/site-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /home/mkoopmans/.local/lib/python3.11/site-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/mkoopmans/.local/lib/python3.11/site-packages (from sympy->torch) (1.3.0)

[notice] A new release of pip is available: 23.1.2 -> 24.2
[notice] To update, run: pip install --upgrade pip
DEVICE COUNT: 4
usage: run.py [-h] --model MODEL --dataset DATASET --split_name SPLIT_NAME
              [--model_dir MODEL_DIR] [--threshold THRESHOLD]
              [--learning_rates LEARNING_RATES]
              [--unlearning_steps UNLEARNING_STEPS]
              [--batch_sizes BATCH_SIZES]
              [--include_learning INCLUDE_LEARNING] [--metric METRIC]
              [--num_repeats NUM_REPEATS]
run.py: error: unrecognized arguments: 5e-8, 1e-7, 5e-7, 1e-6, 5e-6]
DEVICE COUNT: 4
usage: run.py [-h] --model MODEL --dataset DATASET --split_name SPLIT_NAME
              [--model_dir MODEL_DIR] [--threshold THRESHOLD]
              [--learning_rates LEARNING_RATES]
              [--unlearning_steps UNLEARNING_STEPS]
              [--batch_sizes BATCH_SIZES]
              [--include_learning INCLUDE_LEARNING] [--metric METRIC]
              [--num_repeats NUM_REPEATS]
run.py: error: unrecognized arguments: 5e-8, 1e-7, 5e-7, 1e-6, 5e-6]
DEVICE COUNT: 4
DEVICE COUNT: 4
usage: run.py [-h] --model MODEL --dataset DATASET --split_name SPLIT_NAME
              [--model_dir MODEL_DIR] [--threshold THRESHOLD]
              [--learning_rates LEARNING_RATES]
              [--unlearning_steps UNLEARNING_STEPS]
              [--batch_sizes BATCH_SIZES]
              [--include_learning INCLUDE_LEARNING] [--metric METRIC]
              [--num_repeats NUM_REPEATS]
run.py: error: unrecognized arguments: 5e-8, 1e-7, 5e-7, 1e-6, 5e-6]
usage: run.py [-h] --model MODEL --dataset DATASET --split_name SPLIT_NAME
              [--model_dir MODEL_DIR] [--threshold THRESHOLD]
              [--learning_rates LEARNING_RATES]
              [--unlearning_steps UNLEARNING_STEPS]
              [--batch_sizes BATCH_SIZES]
              [--include_learning INCLUDE_LEARNING] [--metric METRIC]
              [--num_repeats NUM_REPEATS]
run.py: error: unrecognized arguments: 5e-8, 1e-7, 5e-7, 1e-6, 5e-6]
E0814 23:44:32.184000 23190449497920 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 2) local_rank: 0 (pid: 286136) of binary: /sw/arch/RHEL8/EB_production/2023/software/Python/3.11.3-GCCcore-12.3.0/bin/python
Traceback (most recent call last):
  File "/home/mkoopmans/.local/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/mkoopmans/.local/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/mkoopmans/.local/lib/python3.11/site-packages/accelerate/commands/launch.py", line 1093, in launch_command
    multi_gpu_launcher(args)
  File "/home/mkoopmans/.local/lib/python3.11/site-packages/accelerate/commands/launch.py", line 734, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/mkoopmans/.local/lib/python3.11/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/mkoopmans/.local/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mkoopmans/.local/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/mkoopmans/MIA-metric-thesisproject/run.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-08-14_23:44:32
  host      : gcn68.local.snellius.surf.nl
  rank      : 1 (local_rank: 1)
  exitcode  : 2 (pid: 286137)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-08-14_23:44:32
  host      : gcn68.local.snellius.surf.nl
  rank      : 2 (local_rank: 2)
  exitcode  : 2 (pid: 286138)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-08-14_23:44:32
  host      : gcn68.local.snellius.surf.nl
  rank      : 3 (local_rank: 3)
  exitcode  : 2 (pid: 286139)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-14_23:44:32
  host      : gcn68.local.snellius.surf.nl
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 286136)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

JOB STATISTICS
==============
Job ID: 7483665
Cluster: snellius
User/Group: mkoopmans/mkoopmans
State: RUNNING
Nodes: 1
Cores per node: 72
CPU Utilized: 00:00:00
CPU Efficiency: 0.00% of 00:46:48 core-walltime
Job Wall-clock time: 00:00:39
Memory Utilized: 0.00 MB (estimated maximum)
Memory Efficiency: 0.00% of 480.00 GB (480.00 GB/node)
WARNING: Efficiency statistics may be misleading for RUNNING jobs.
